### ISSUE TITLE
Cannot export navmesh.

### ISSUE THREAD

**Issue by sunset-developer** [donmccurdy/aframe-inspector-plugin-recast#41]
Recently, I cannot export the navmesh in the inspector. Strangely I have changed nothing since last working on my project but suddently I keep getting the error below which is preventing me from exporting my build navmesh. 

```
aframe-inspector.min.js:25 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at C (aframe-inspector.min.js:25:175584)
    at k (aframe-inspector.min.js:25:178934)
    at S (aframe-inspector.min.js:25:179479)
    at A (aframe-inspector.min.js:25:179632)
    at aframe-inspector.min.js:25:180130
    at THREE.GLTFExporter.parse (aframe-inspector.min.js:25:180232)
    at RecastPlugin.exportGLTF (aframe-inspector-plugin-recast.js:9046:14)
    at HTMLButtonElement.<anonymous> (aframe-inspector-plugin-recast.js:8881:54)
```

```html
<!doctype html>
<html>
    <head>
        <script src="https://aframe.io/releases/0.8.2/aframe.min.js"></script>
        <script src="https://cdn.jsdelivr.net/gh/donmccurdy/aframe-extras@v6.1.1/dist/aframe-extras.min.js"></script>
        <script src="https://recast-api.donmccurdy.com/aframe-inspector-plugin-recast.js"></script>
        <script src="https://rawgit.com/fernandojsg/aframe-teleport-controls/master/dist/aframe-teleport-controls.min.js"></script>
    </head>
    
    <body>
        <a-scene background="color: #FFFFFF" inspector-plugin-recast>
        </a-scene>
    </body>
</html>
```

Assistance would be appreciated thanks.

**Comment by donmccurdy** [comment]
Hi @sunset-developer — see https://github.com/donmccurdy/aframe-inspector-plugin-recast/pull/47. Unfortunately the dependencies of this project are pretty old, and the lack of a stable and documented Recast WASM build has become a big obstacle. I'm no longer able to keep this project working locally. 😞
